filebeat.inputs:
- type: log
  paths:
  - '/home/kali/elk/aps/*.csv'
  exclude_lines: ['^"?BSSID"?,"?channel"?,"?Privacy"?,"?Cipher"?,"?Authentication"?,"?ESSID"?']

output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  index: "local-aps"
  pipeline: "local-aps-pipeline"

setup:
  template.enabled: false
  ilm.enabled: false
  template.name: "local-aps"
  template.pattern: "local-aps-pipeline"
