filebeat.inputs:
- type: log
  paths:
  - '/home/kali/elk/aps/*.csv'
  exclude_lines: ['^"?BSSID"?,"?First time seen"?,"?Last time seen"?,"?channel"?,"?Speed"?,"?Privacy"?,"?Cipher"?,"?Authentication"?,"?Power"?,"?# beacons"?,"?# IV"?,"?LAN IP"?,"?ID-length"?,"?ESSID"?,"?Key"?']

processors:
- add_locale: ~

output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  index: "local-aps"
  pipeline: "local-aps-pipeline"

setup:
  template.enabled: false
  ilm.enabled: false
  template.name: "local-aps"
  template.pattern: "local-aps-pipeline"