filebeat.inputs:
- type: log
  paths:
  - '/home/kali/elk/clients/*.csv'
  exclude_lines: ['^"?Client MAC"?,"?First time seen"?,"?Last time seen"?,"?Power"?,"?# packets"?,"?BSSID"?,"?ESSID"?']

processors:
- add_locale: ~

output.elasticsearch:
  hosts: ["127.0.0.1:9200"]
  index: "local-clients"
  pipeline: "local-clients-pipeline"

setup:
  template.enabled: false
  ilm.enabled: false
  template.name: "local-clients"
  template.pattern: "local-aps-clients"